<!DOCTYPE html>
<html>
    <body>
        <footer>
            <!-- footer with copyright and other details, along with the link to the Jira board. -->
            <p id="footercopy" style="font-size:1vw">&copy; Copyright Save the Krill 1830-2025 &trade; &reg;  
            <a href="https://lachiecolville.atlassian.net/jira/software/projects/T2G/boards/34/backlog?epics=visible&jql=parent%20IN%20%28__OPTIMISTIC_UI__%2C%20empty%2C%20T2G-7%2C%20T2G-7%2C%20T2G-8%29">Jira</a> </p>
            <p style="font-style: italic; font-size:1vw">
                <strong>Github:</strong> 
                <a href="https://github.com/106257239/webtechassignmentpt2">https://github.com/106257239/webtechassignmentpt2</a>.
            </p>
            <!-- Contact info -->
            <!-- <aside id="about_aside"> -->
            <p style="font-style: italic; font-size:1vw">
                <strong>Note:</strong> This is a student project for Swinburne.  
                For inquiries, contact us at 
                <a href="mailto:savetheshrimps@project.com">savetheshrimps@project.com</a>.
            </p>
            <!-- </aside> -->
        </footer>
    </body>
</html>