<!DOCTYPE html>
<html>
    <body>
        <footer>
            <!-- footer with copyright and other details, along with the link to the Jira board. -->
            <p id="footercopy">&copy; Copyright Save the Krill 1830-2025 &trade; &reg;  
            <a href="https://lachiecolville.atlassian.net/jira/software/projects/T2G/boards/34/backlog?epics=visible&jql=parent%20IN%20%28__OPTIMISTIC_UI__%2C%20empty%2C%20T2G-7%2C%20T2G-7%2C%20T2G-8%29">Jira</a> </p>
        </footer>
    </body>
</html>