<!DOCTYPE html>
<html>
    <header>
        <!-- IMG SOURCED FROM https://www.freepik.com/ USER: Catalyst stuff  full link: https://www.freepik.com/free-vector/cute-chef-shrimp-cartoon-vector-icon-illustration-animal-food-icon-concept-isolated-premium-vector_26259299.htm#fromView=keyword&page=1&position=0&uuid=eae536ac-f070-4e07-a549-7e5f0fb771f4&query=Shrimp+chef-->
        <img src="styles/images/shrimp_no_bg.png"; alt="a cartoon shrimp"; title="Save The Shrimp"; id="shrimp">
        <!--links heading text to index page -->
        <a href="index.html"><h1>Save The Krill</h1></a>
        <!--empty p tag for equal spacing in flexbox  -->
        <p></p>
    </header>
</html>