<!DOCTYPE html>
<html>
    <body>
        <nav>
            <!--nav sey up as list for styling purposes-->
            <ul>
            <!--links to each page of website with _self as target to open on same page-->
                <li style="font-size:2vw"><a href="./index.php" target="_self" title="Index" hreflang="english" >Home Page</a></li>
                <li style="font-size:2vw"><a href="./about.php" target="_self" title="About Page" hreflang="english">About Us</a></li>
                <li style="font-size:2vw"><a href="./jobs.php" target="_self" title="Jobs Page" hreflang="english">Jobs</a></li>
                <li style="font-size:2vw"><a href="./apply.php" target="_self" title="Apply page" hreflang="english">Volunteer</a></li>
                    <li><a href="manage.php" title="manage page" hreflang="english">login </a></li>
            </ul>
        </nav>
    </body>
</html>
