<!DOCTYPE html>
<html>
    <nav>
        <!--nav sey up as list for styling purposes-->
        <ul>
        <!--links to each page of website with _self as target to open on same page-->
            <li><a href="./index.html" target="_self" title="Home Page" hreflang="english" >Home Page</a></li>
            <li><a href="./about.html" target="_self" title="About Page" hreflang="english">About Us</a></li>
            <li><a href="./jobs.html" target="_self" title="Jobs Page" hreflang="english">Jobs</a></li>
            <li><a href="./apply.html" target="_self" title="Apply page" hreflang="english">Volunteer</a></li>
        </ul>
    </nav>
</html>